# Generated by Django 4.2.4 on 2023-08-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RenameField(model_name="resume", old_name="files", new_name="file",),
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="job",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="home.job"
            ),
            preserve_default=False,
        ),
    ]
