# Generated by Django 4.2.4 on 2023-08-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_job_rename_files_resume_file_alter_resume_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="shortlisted",
            field=models.BooleanField(default=False),
        ),
    ]
