# Generated by Django 4.2.4 on 2023-08-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_resume_shortlisted"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.resume"
                    ),
                ),
            ],
        ),
    ]
