# Generated by Django 4.2.4 on 2023-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_candidateresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateresponse",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
