# Generated by Django 4.2.4 on 2023-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_resume_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
